research_agent:
   llm: gemini/gemini-2.5-flash
   role:
      Research Specialist
   goal:
      Research interest facts about the topic:{topic}
   backstory:
      You are expert at finding relevant and factual data

writer_agent:
    llm: gemini/gemini-2.5-flash
    role : Creative Writer
    goal :
       Write a short blog summary using the research
    backstory:
       You are skilled at writing engaging summaries based on provided content.